### PR TITLE
changed a to link

### PR DESCRIPTION
**Pull request by draunger**
## Description
[Provide a brief description of the changes made in this pull request.]

## Motivation and Context
[Explain the motivation behind these changes and provide any relevant context.]

## How to Test
[Describe the steps to test the changes made in this pull request.]

## Related Issues
[If applicable, mention any related issues or pull requests.]

## Checklist
- [ ] I have tested these changes locally.
- [ ] I have reviewed the code and ensured it follows the project's coding guidelines.
- [ ] I have updated the documentation, if necessary.
- [ ] I have assigned reviewers to this pull request.

## Screenshots (if applicable)
[If your changes include any visual updates, provide screenshots here.]

### CODE REVIEW

**Comment by kuv2707** [comment]
Please fix the failing test. Perhaps you forgot to import Link from react-router-dom

**Comment by kuv2707** [comment]
Please fix the prettier check (running npm run fix-format)
Also,
The changes should be done in the same commit - so that it passes all the checks.
You can refer to CONTRIBUTING.MD for how to edit commits. You can ask doubts here.

**Comment by kuv2707** [comment]
Please restructure your commits so that all the changes are there in one commit. You can `squash` the commits.

**Comment by kuv2707** [comment]
@draunger The commit message doesn't follow the guidelines. 
I am editing it myself, but please note that henceforth.

Also once you make changes and want a review, do tag a maintainer.

**Comment by kuv2707** [comment]
Merged, thanks @draunger

**Comment by draunger** [comment]
@kuv2707 thanks

**Pull request merged**
