### PR TITLE
Client:Implemented the input component

### PR DESCRIPTION
**Pull request by ritwik-69**
fixes:#77

## Description
Created the Input component as discussed and made in figma. As props it takes normal input properties like placeholder,value etc. The styling has been done in input.css (I had to rename it input.css from input.module.css as it was not working when importing)

## Motivation and Context
[Explain the motivation behind these changes and provide any relevant context.]

## How to Test
[Describe the steps to test the changes made in this pull request.]

## Related Issues
[If applicable, mention any related issues or pull requests.]

## Checklist
- [x] I have tested these changes locally.
- [x] I have reviewed the code and ensured it follows the project's coding guidelines.
- [ ] I have updated the documentation, if necessary.
- [ ] I have assigned reviewers to this pull request.

## Screenshots (if applicable)
[If your changes include any visual updates, provide screenshots here.]

image

input code

### CODE REVIEW

**Comment by shivansh-bhatnagar18** [comment]
@ritwik-69 Can you please use tailwind for styling of components as much as possible? Also I am configuring Kavoom to the tailwind file so change the fonts accordingly.

**Comment by ritwik-69** [comment]
@shivansh-bhatnagar18 I used tailwing css and configured it to include kavoon font

**Comment by kuv2707** [comment]
@ritwik-69 Please update the screenshots, and rebase your branch once (against upstream/master)

**Comment by ritwik-69** [comment]
@kuv2707 done with the changes

**Comment by shivansh-bhatnagar18** [comment]
@ritwik-69 Please fix the merge conflicts. The component looks good but add some basic parameters as width and height as parameters. Also remove the related input CSS files because you are already using tailwind

**Comment by ritwik-69** [comment]
@shivansh-bhatnagar18 I don't understand why vercel deployment is failing?

**Comment by shivansh-bhatnagar18** [comment]
@ritwik-69 You are still importing ./input.css in the input.tsx. To check why this deployment fails try running npm run build

**Comment by shivansh-bhatnagar18** [comment]
@ritwik-69 Please change the font to kavoon

**Pull request merged**
