### PR TITLE
Frontend: Display The Player Whose Turn It Is Currently

### PR DESCRIPTION
**Pull request by asmit27rai**
## Description
1. Brightened player icons for active turn indication.

2. Displayed current player's name on game board.

4. Tailwind CSS utility classes have been applied for consistent styling of the player's name.

## Checklist
- [x] I have tested these changes locally.
- [x] I have reviewed the code and ensured it follows the project's coding guidelines.
- [ ] I have updated the documentation, if necessary.
- [ ] I have assigned reviewers to this pull request.

## Screenshots
Screenshot 2024-06-27 000533

### CODE REVIEW

**Comment by kuv2707** [comment]
Just to be clear, we display every player's name below the cards, and in a separate place, display the name of the player currently having turn, right?

**Comment by kuv2707** [comment]
Both of these things are being tracked in separate issues, and this one deals with displaying the current player's name in some central location.

**Comment by asmit27rai** [comment]
> Just to be clear, we display every player's name below the cards, and in a separate place, display the name of the player currently having turn, right?

Yes ,here it will showing the player's name currently having turn.

**Comment by asmit27rai** [comment]
> Both of these things are being tracked in separate issues, and this one deals with displaying the current player's name in some central location.

So should i show the name of player currently having turn at center of board or where?

**Comment by kuv2707** [comment]
We should display the current player's name in some central location.
All the individual players will also have their names displayed

**Comment by asmit27rai** [comment]
> We should display the current player's name in some central location. All the individual players will also have their names displayed

OK I will update the PR accordingly.

**Comment by asmit27rai** [comment]
Done With All The Changes.

**Comment by kuv2707** [comment]
This works for now, thanks @asmit27rai

**Pull request merged**
