### PR TITLE
engine: Implement Card Allotment Logic

### LINKED ISSUE #3: Implement card allotment logic
# Description
The allotCards function needs to distribute `NUM_CARDS_PER_PLAYER` cards from the deck to each player's hand.

Current Code Snippet
```javascript
allotCards() {
    //todo: Implement the card allotment logic: Remove `NUM_CARDS_PER_PLAYER` cards from the deck and add them to the player's hand - Do this for each player
    // example:
    this.players[0].cards = this.cardDeck.splice(0, NUM_CARDS_PER_PLAYER);
}
```
# Expected Output
Each player should receive NUM_CARDS_PER_PLAYER cards from the deck. Note that the distributed cards are removed from the deck.
# Notes
Ensure the function works for any number of players.

### PR DESCRIPTION
**Pull request by criticic**
This adds a check to ensure there are enough cards in the deck to allot to all players. And then distributes the cards to all players from the shuffled deck.

Fixes #3

<details>
<summary>Screenshots and screen captures</summary>
</details>

<details>
<summary>Self-review checklist</summary>

- [x] Self reviewed the changes for clarity and maintainability (variable names, code reuse, readability, etc.).
- [x] Highlights technical choices and bugs encountered.
- [ ] Calls out remaining decisions and concerns.
- [ ] Automated tests verify logic where appropriate.
- [x] Each commit is a coherent idea.
- [x] Commit message(s) explain reasoning and motivation for changes.

Completed manual review and testing of the following:

- [NA] Visual appearance of the changes.
- [NA] End-to-end functionality of buttons, interactions and flows.
- [x] Corner cases, error conditions, and easily imagined bugs.
</details>

### CODE REVIEW

**Comment by shivansh-bhatnagar18** [comment]
@criticic Can you resolve the merge conflicts and fix the Lints/Formatting. Your code LGTM otherwise and ready to be merged

**Comment by criticic** [comment]
I dont get any lint errors locally, I think it might have been due to the unused variable thing

**Comment by criticic** [comment]
I fixed the other PR too, i think it'll work fine now

**Comment by shivansh-bhatnagar18** [comment]
@criticic There were Prettier Issues but I'll fix that for now

**Pull request merged**
