### PR TITLE
Fix/issue #61

### PR DESCRIPTION
**Pull request by ritwik-69**
# fixes: #61 

## Description
Created the sending events to all the eligible clients with the response object.

## Motivation and Context
[Explain the motivation behind these changes and provide any relevant context.]

## How to Test
[Describe the steps to test the changes made in this pull request.]

## Related Issues
[If applicable, mention any related issues or pull requests.]

## Checklist
- [ ] I have tested these changes locally.
- [ ] I have reviewed the code and ensured it follows the project's coding guidelines.
- [ ] I have updated the documentation, if necessary.
- [ ] I have assigned reviewers to this pull request.

## Screenshots (if applicable)
[If your changes include any visual updates, provide screenshots here.]

### CODE REVIEW

**Comment by kuv2707** [comment]
image


The commit message doesn't need to mention anything about intermediate edits/changes

**Comment by ritwik-69** [comment]
@kuv2707 should i change the commit message?

**Comment by kuv2707** [comment]
Yes

**Comment by kuv2707** [comment]
Closing in favor of #66 
Thanks for all the work @ritwik-69

**Pull request closed without merging**
