### PR TITLE
Added a scrollbar and improved the responsiveness of the website

### PR DESCRIPTION
**Pull request by realnilesh**
## Description
I have added a scrollbar with gradient colour and also fixed the css and changes some classes as well to make the site more responsive

## How to Test
Migrate to the frontnd directory on command line and type npm run dev to run the frontend.

## Checklist
 - I have tested these changes locally.
-  I have reviewed the code and ensured it follows the project's coding guidelines.
- [ ] I have updated the documentation, if necessary.
- [ ] I have assigned reviewers to this pull request.

## Screenshots (if applicable)
laptop view without scrollbar hover
Screenshot (115)

large (laptop view) scrollbar with hover
Screenshot (116)

mobile view(s20 ultra)
Screenshot 2024-06-15 022912

mobile view(14 pro max)
Screenshot 2024-06-15 022929

### CODE REVIEW

**Comment by realnilesh** [comment]
Edited some css styles further for a better phone view

on Iphone 14 pro max
Screenshot 2024-06-15 120249


on samsung s20 ultra

Screenshot 2024-06-15 120301

**Comment by kuv2707** [comment]
@shivansh-bhatnagar18 Please have a look.
I don't know if there is a need to change any other file than .css

**Comment by realnilesh** [comment]
> @shivansh-bhatnagar18 Please have a look.
> I don't know if there is a need to change any other file than .css

Bhaiya the other files are changed just to improve the responsiveness , as i was already working on it but wasn't assigned to. If you just need scrollbar only index.css must be modified

**Comment by kuv2707** [comment]
@realnilesh You should only stick to changes specified in the issue. 
I think the responsiveness is being dealt with in a separate PR.
You can remove all but the css file changes from this PR.

**Comment by realnilesh** [comment]
> @realnilesh You should only stick to changes specified in the issue. I think the responsiveness is being dealt with in a separate PR. You can remove all but the css file changes from this PR.

done bhaiya

**Pull request closed without merging**
