### PR TITLE
ErrorPage: created 404 Page Not Found page

### PR DESCRIPTION
**Pull request by sethdivyansh**
Fixes: #21 

## Description
This commit adds a UNO theme 404 page not found page.
 Ensured the page is fully responsive for various devices. 
Included Page not Found error message and navigation link back to the homepage.

## How to Test
Start the frontend and go to any page that does not exists.

## Checklist
- [x] I have tested these changes locally.
- [x] I have reviewed the code and ensured it follows the project's coding guidelines.
- [ ] I have updated the documentation, if necessary.
- [ ] I have assigned reviewers to this pull request.

## Screenshots (if applicable)
Screenshot 2024-06-03 at 2 57 24 AM
<br>
<h3>On hover:</h3>
image
<br>
<h3>small screen devices</h3>
Screenshot 2024-06-03 at 2 58 51 AM

### CODE REVIEW

**Comment by kuv2707** [comment]
Awesome design!
@shivansh-bhatnagar18 please chime in

**Review by ApoorvDubey23 — APPROVED** [review]
Good Design

**Comment by shivansh-bhatnagar18** [comment]
LGTM

**Comment by sethdivyansh** [comment]
@shivansh-bhatnagar18 I have resolved the prettier issue.

**Pull request merged**
