### PR TITLE
Client: Added a Scrollbar 

### PR DESCRIPTION
**Pull request by realnilesh**
## Description
Added a funky scollbar which which changes gradient by 60deg

## How to Test
navigate to frontend directory and run the "npm run dev " commmand

## Checklist
-  I have tested these changes locally.
-  I have reviewed the code and ensured it follows the project's coding guidelines.
- [ ] I have updated the documentation, if necessary.
- [ ] I have assigned reviewers to this pull request.

## Screenshots (if applicable)
scrollbar without hover
Screenshot (115)

scrollbar with hover
Screenshot (116)

### CODE REVIEW

**Comment by kuv2707** [comment]
@shivansh-bhatnagar18 There's some issue with vercel deployments.

Also please review the design of the scrollbar.


@realnilesh Please change the commit message to match the format.

**Comment by kuv2707** [comment]
You can run `npm fun fix-format` in the frontend directory to fix all the prettier errors.

**Comment by realnilesh** [comment]
> You can run `npm fun fix-format` in the frontend directory to fix all the prettier errors.

Ran the above command to make the commit pass prettier check

**Comment by kuv2707** [comment]
The changes look good, but the commits are messed up.

Do take the time to learn how to edit commit history and also read the docs for some examples and tutorials.

**Comment by kuv2707** [comment]
Squashed and merged, thanks @realnilesh

**Comment by realnilesh** [comment]
> Squashed and merged, thanks @realnilesh 

My pleasure bhaiya

**Comment by realnilesh** [comment]
> The changes look good, but the commits are messed up.
> 
> Do take the time to learn how to edit commit history and also read the docs for some examples and tutorials.

Surely I will learn and improve ,this was my first time contributing to open source

**Pull request merged**
