### PR TITLE
Frontend: Modify PlayOptions.tsxfile.     Here,in this modification,I…

### PR DESCRIPTION
**Pull request by asmit27rai**
### Work On **PlayOptions.tsx** 
Fixes : #23

## Description
I worked on PlayOptions.tsx using components from library folders like buttom and Input.
Also Worked On heading.tsx to use as component by adding heading.module.css file for css of heading component.

## Checklist
- [x] I have tested these changes locally.
- [x] I have reviewed the code and ensured it follows the project's coding guidelines.
- [ ] I have updated the documentation, if necessary.
- [ ] I have assigned reviewers to this pull request.

### CODE REVIEW

**Comment by kuv2707** [comment]
@Varun-Kolanu @shivansh-bhatnagar18 Please take a look.

**Comment by shivansh-bhatnagar18** [comment]
@asmit27rai Can you please work on the conflicts and Linting for this PR. Thanks

**Comment by asmit27rai** [comment]
> @asmit27rai Can you please work on the conflicts and Linting for this PR. Thanks

I want to modify this PR. 
What to do with button component as it is still not completed? Since I have to use it for making good ui.

**Comment by kuv2707** [comment]
@asmit27rai Thanks for the PR, but since the issue is completed, we'd have to close the PR.

**Pull request closed without merging**
