### PR TITLE
Frontend: designed a custom button component based on figma design

### PR DESCRIPTION
**Pull request by sksmagr23**
## Description
I have created a customizable and reusable button based on the given figma design, in src/library.
I have used all possible input props and styled using tailwind css and added some custom pluggins and css as required.

Fixes: #76

## Related Issues
- #76 

## Checklist
- [x] I have tested these changes locally.
- [x] I have reviewed the code and ensured it follows the project's coding guidelines.
- [x] I have updated the documentation, if necessary.
- [x] I have assigned reviewers to this pull request.

## Screenshots 
Screenshot from 2024-06-08 09-38-48

### CODE REVIEW

**Comment by sksmagr23** [comment]
@shivansh-bhatnagar18 please review and merge these changes, so that other components can be made

**Comment by kuv2707** [comment]
@sksmagr23 Please rebase you branch once.

**Comment by sksmagr23** [comment]
Done rebasing with upstream

**Comment by kuv2707** [comment]
@shivansh-bhatnagar18 Please have a look.

**Comment by shivansh-bhatnagar18** [comment]
@sksmagr23 Thanks for the PR. The button component looks great

**Pull request merged**
