### PR TITLE
Server: JWT Auth for login and register

### LINKED ISSUE #62: Implement JWT Authentication for User login and registration
# Description:
We need to implement JWT authentication in our application. This should be done using React for the frontend, Node.js and Express for the backend, and MongoDB for the database.

# Specs
- A `UserModel` should be created at `models/userModel.ts`. You can use the `mongoose` library.
Currently, it suffices to add the fields `name` and `password` to it.
- There should be an authentication middleware, which adds `user` object to the Request object.
- There should be handlers for `/login` and `/register`, possibly sharing the verification logic with the middleware.
- The user should be signed in immediately after registering.

# Notes
- Please refer to `ARCHITECTURE.md` before starting any work.

### PR DESCRIPTION
**Pull request by asmit27rai**
### JWT Authentication For Login And Register Route

Fixes #62

## Description
Implement authMiddleware for login and register authentication with jsonwebtoken and bcrypt that store password in hashed form in database and check accordingly during login and also set routes for login and register in userRoutes

## Motivation and Context
[Explain the motivation behind these changes and provide any relevant context.]

## How to Test
Steps For Testing:
1. Setup Your Mongodb database.
2. In Postman try with same route for register and login using the same model as set in userModel.js file.

## Checklist
- [x] I have tested these changes locally.
- [x] I have reviewed the code and ensured it follows the project's coding guidelines.
- [ ] I have updated the documentation, if necessary.
- [ ] I have assigned reviewers to this pull request.

### CODE REVIEW

**Comment by kuv2707** [comment]
@asmit27rai This seems promising. 
Please squash the commits and implement an auth middleware.

Also, we should wrap all handlers in `utils::catchError`.

**Comment by asmit27rai** [comment]
> @asmit27rai This seems promising. Please squash the commits and implement an auth middleware.
> 
> Also, we should wrap all handlers in `utils::catchError`.

Done.

**Comment by kuv2707** [comment]
@asmit27rai There are some unrelated (frontend) changes in the PR.
I think you squashed some commits already in upstream/master, since evidently, the commit is authored by Shivansh.

Try rebasing agains upstream/master and discarding the changes not made by you.

And while you are at it, please amend the commit message to occupy around 72 characters per line
You can put the details as points to make it easier to read.

We should get done with this as fast as possible

**Comment by asmit27rai** [comment]
> @asmit27rai There are some unrelated (frontend) changes in the PR. I think you squashed some commits already in upstream/master, since evidently, the commit is authored by Shivansh.
> 
> Try rebasing agains upstream/master and discarding the changes not made by you.
> 
> And while you are at it, please amend the commit message to occupy around 72 characters per line You can put the details as points to make it easier to read.
> 
> We should get done with this as fast as possible

Done from my side.

**Comment by kuv2707** [comment]
@asmit27rai There are still merge conflicts.

Closing this as completed via a different PR, thanks for all the work!

**Pull request closed without merging**
