### PR TITLE
Frontend: Added a Playoptions page

### PR DESCRIPTION
**Pull request by sksmagr23**
## Description
This commit add a playoptions page that renders onn navigating to /play. It has been created using Heading and button components of library and custom styling is done using Tailwind css and also added a UNO game logo, the page is fully responsive with a uno theme design

## How to Test
-Run npm run dev under frontend directory, and navigate to /play

## Related Issues
-fix/issue #23

## Checklist
- [x] I have tested these changes locally.
- [x] I have reviewed the code and ensured it follows the project's coding guidelines.
- [x] I have updated the documentation, if necessary.
- [x] I have assigned reviewers to this pull request.

## Screenshots 
Screenshot from 2024-06-04 15-08-40

### CODE REVIEW

**Comment by sksmagr23** [comment]
@kuv2707 and @shivansh-bhatnagar18 please review,this time I have well addressed the commits and checks

**Comment by ApoorvDubey23** [comment]
This will be merged after the creation of Heading and button component i.e. after #67 and #20 are done .Make sure to integrate both of the components in your code afterwards.

**Comment by shivansh-bhatnagar18** [comment]
Thanks @sksmagr23 for the pull request. I am merging it for now on but this needs a lot of refinement.

**Comment by kuv2707** [comment]
@sksmagr23 Please be motivated to refactor this area of code with library components as they are added.

They can be done through future PRs.

**Pull request merged**
